name: Next.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Ensure yarn.lock exists
        run: |
          if [ ! -f yarn.lock ]; then
            echo "yarn.lock not found, generating one..."
            yarn install --no-lockfile
          fi

      - name: Install dependencies
        run: yarn install --frozen-lockfile || yarn install --no-lockfile

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test
